### ISSUE TITLE
There doesnt seem to be any security over webhooks

### ISSUE THREAD

**Issue by tyson-benson** [chipwillman/VendAPI.Net#1]
Is it true that Vend provides no way to challenge the authenticity of a HTTP POST request made via their webhooks? I can see no verification steps in the VendHook project.

**Comment by chipwillman** [comment]
The web hook is designed to call out to a 3rd party server.  Vend is sending information not receiving it so there is no verification step associated with a web hook.  To setup the web hook, you must authenticate against their web site.

The service that is consuming the webhook call, in this project that is the printing of meal tickets in the Kitchen, should protect itself from unauthorized access through the firewall.  When forwarding the port to your web server, limit the ip range that only vend.com (5.22.0.0/16 or even tighter 5.22.149.0/24) can post to your incoming port.

If you are unable to limit the port range then yes, there is no way to tell if a HTTP POST to your service is authentic or not at the moment.

**Comment by tyson-benson** [comment]
So it seems unfortunately Vend haven't come to the party on providing secure webhook notifications. There are [many](http://help.mandrill.com/entries/23704122-Authenticating-webhook-requests) [implementations](https://trello.com/docs/gettingstarted/webhooks.html) [of](http://docs.shopify.com/api/tutorials/using-webhooks#verify-webhook) [webhooks](http://pusher.com/docs/webhooks) that do secure the messages by signing them with a HMAC SHA-256 digest of the payload and a shared secret/private key.

I don't think IP based authorization is acceptable given the change of [IP spoofing attacks](http://en.wikipedia.org/wiki/IP_address_spoofing). Note that Wikipedia lists "Any service that uses IP address authentication" as vulnerable to IP spoofing attacks.

I've brought this issue up with Vend, hopefully I'll hear from them soon. Thanks for your work by the way.

**Comment by pulkitsinghal** [comment]
@tyson-benson I secured it by adding a query-parameter to the webhook URL I paste into vend like `https://send-webhook.tome.com/api/product/endpoint?token=abcd` and making sure that I check that `token` in the server which receives the webhook payload before proceeding. It worked quite well.

At the time (2013?) I wrote it, vend did not let me add webhooks programmatically so provisioning manually by copy/pasting into customer accounts was a pain but then they added APIs for webhooks so I think its quite allright now.

**Comment by Yusha813** [comment]
Vend claims you can use verification for the Webhook Requests they send. Unfortunately, they don't send any type of Signature Header... All they send is a X-Vend-Webhook-Id. You can see [here ](https://docs.vendhq.com/docs/webhooks)

**Comment by Yashuaaa** [comment]
@pulkitsinghal  @tyson-benson You shouldn't put the Access Token in the URL of a Webhook... That could be easily intercepted / comprimised. Vend now will send a **Signature** [header ](https://docs.vendhq.com/docs/webhooks)that you can use to compare against the Webhook request body to see if the request is authentic or not. There is one issue though, if you are not using **OAuth** (convoluted, hits the **Vend server** an unnecessary amount of times) then you are out of luck. When using a personal Access Token, for some reason, the Vend developers decided to **not** send a **Signature** header with the associated Webhook **POST.** It's pretty annoying.
